# disable the bell sound
enable_audio_bell no


# cursor block 
cursor_shape block

shell_integration no-cursor


# Zoom in with Ctrl + Plus
map ctrl+shift+= increase_font_size

# Zoom out with Ctrl + Minus
map ctrl+shift+- decrease_font_size

# Restablecer el tamaño de fuente al valor original
map ctrl+shift+0 set_font_size 12

